GET  http://localhost:4000/api/chats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODE1OTYzMDY1MTZmYmY1NmY3NzI2NSIsImlhdCI6MTY3ODMxNDY2MSwiZXhwIjoxNjgwOTA2NjYxfQ.G00OG4vxkaz3POwZrjyMPk0Z9dFAOyX5wUtJXmye4oo

{
    "userId": "6381596306516fbf56f77265"
}